// E-Commerce Backend API
//
// @title           E-Commerce Backend API
// @version         1.0
// @description     REST API for users, products, carts, and orders.
// @host            localhost:8080
// @BasePath        /api/v1
// @schemes         http
// @accept          json
// @produce         json
//
// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/Isaiah-peter/e-commerce-backend/pkg/routes"

	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"

	// Swagger docs (generated by swag init)
	docs "github.com/Isaiah-peter/e-commerce-backend/docs"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	host := os.Getenv("HOST")
	if host == "" {
		host = "localhost"
	}

	// Configure Swagger metadata at runtime (optional overrides of annotations)
	docs.SwaggerInfo.Title = "E-Commerce Backend API"
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Description = "REST API for users, products, carts, and orders."
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http"}
	docs.SwaggerInfo.Host = fmt.Sprintf("%s:%s", host, port)

	r := mux.NewRouter()

	// Swagger UI endpoint: http://host:port/swagger/index.html
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	subRouter := r.PathPrefix("/api/v1").Subrouter()
	routes.AuthUser(subRouter)
	routes.UserRoute(subRouter)
	routes.Product(subRouter)
	routes.OrderRoute(subRouter)
	routes.CartRoute(subRouter)

	address := fmt.Sprintf("%s:%s", host, port)
	log.Println("server running on", address)
	log.Fatal(http.ListenAndServe(address, handlers.CORS(
		handlers.AllowedHeaders([]string{"Content-Type", "Authorization"}),
		handlers.AllowedMethods([]string{"GET", "POST", "PUT", "HEAD", "OPTIONS", "DELETE"}),
		handlers.AllowedOrigins([]string{"*"}),
	)(r)))
}
